Add Dutch (and Belgian Dutch) matching labels
PhilippRecke/Autocomplete-Check pull request #3
Opened 2024-02-23 21:05 UTC by roelvangils

This pull request adds Dutch (Netherlands) and Belgian Dutch language labels to your extension. These labels have been tested on some internal sample pages and work as expected. Thank you for considering this merge request! If you approve, we can also add French labels.

2024-02-23 22:57 UTC, PhilippRecke commented
Hi, thank you very much for your contribution, which is greatly appreciated! I will go over the PR and add some comments.
The plugin needs additional logic in "matchingclasses.ts", as supported languages are currently hardcoded into the matching algorithm. I will add this in the coming days.
Feel free to create another PR for French, I'll be happy to add it as well. The more languages supported, the better. :)

2024-02-23 23:06 UTC, PhilippRecke requested changes

2024-02-23 23:06 UTC, PhilippRecke commented on src/matching/autocomplete-dict.json
> +            "thuisnummer",
Please remove trailing comma. Causes JSON parsing error.

2024-02-23 23:06 UTC, PhilippRecke commented on src/matching/autocomplete-dict.json
> +            "log in",
Just an FYI: the plugin sanitizes all dictionary strings, thus removing whitespaces beforehand. "login" and "log in" will result in the same matching-string. However, this does not affect the outcome at all.

2024-02-23 23:06 UTC, PhilippRecke commented on src/matching/autocomplete-dict.json
> +            "jaar"
Possibly too generic. Might cause false positive matches, if the input is actually of type "cc-exp-year". I personally would opt to remove "jaar" from this list.

2024-02-28 21:32 UTC, roelvangils commented
@PhilippRecke, thank you for reviewing the PR and providing feedback. It's been busy, so I haven't had a chance to address the comments or add the French strings yet. I hope to do it this week! 🙂

2024-08-02 20:02 UTC, roelvangils commented
Hi @PhilippRecke, I'm so sorry that it too so incredibly long to fix these minor things. I just totally got off my radar! 🙊 I know have more time to also add the French labels.

2024-08-03 20:47 UTC, PhilippRecke commented
Hi, totally fine, I lost track of it too. Again, thank you very much! If you want to invest the time to add French, that would still be awesome! :)
Do you think it would make sense to add the ability to enable/disable the languages to match against individually in the settings?
Or is it for your usecase ideal to allways check for all languages at the same time?

2024-08-03 20:47 UTC, merged

2024-08-04 14:06 UTC, roelvangils commented
> Do you think it would make sense to add the ability to enable/disable the languages to match against individually in the settings? Or is it for your usecase ideal to allways check for all languages at the same time?

That's a very good question. I don't think it will ever be necessary to test different language labels on the same page. However, ideally the label checks should be activated based on the language that is identified in the HTML tag, right?